/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Project;

/**
 *
 * @author Avell
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    
    ProjectController projectController;
    TaskController taskController;
    
    //Modelo do componente visual que faz a construção da parte visual
    //Model do componente gráfico
    //Irá guardar as informações (projects) que o método loadProjects() irá trazer
    DefaultListModel<Project> projectModel;
    
    public MainScreen() {
        initComponents();
        setLocationRelativeTo(null);
        decorateTableTask();
        //Chama o método que instanciou os dois controllers
        initDataController();
        //Chama o método que instanciou o projectModel e dá o load nos projects
        initComponentsModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListaVazia = new javax.swing.JPanel();
        jLabelTarefaSelecionadaIconFundo = new javax.swing.JLabel();
        jLabelNenhumaTarefa = new javax.swing.JLabel();
        jLabelCliqueNoBotao = new javax.swing.JLabel();
        JPanelFundoGeral = new javax.swing.JPanel();
        jPanelTopo = new javax.swing.JPanel();
        jLabelDeadLineApp = new javax.swing.JLabel();
        jLabelAnote = new javax.swing.JLabel();
        jPanelFundoProjeto = new javax.swing.JPanel();
        jLabelProjetos = new javax.swing.JLabel();
        jLabelProjetosAddIcon = new javax.swing.JLabel();
        jPanelFundoTarefa = new javax.swing.JPanel();
        jLabelTarefas = new javax.swing.JLabel();
        jLabelTarefasAddIcon = new javax.swing.JLabel();
        jPanelFundoListaItem = new javax.swing.JPanel();
        jScrollPaneProjetos = new javax.swing.JScrollPane();
        jListProjetos = new javax.swing.JList<>();
        jPanelFundoTarefaSelecionada = new javax.swing.JPanel();
        jScrollPaneTarefas = new javax.swing.JScrollPane();
        jTableListaTarefas = new javax.swing.JTable();

        jPanelListaVazia.setBackground(java.awt.Color.white);

        jLabelTarefaSelecionadaIconFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTarefaSelecionadaIconFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list/xxhdpi-lists.png"))); // NOI18N

        jLabelNenhumaTarefa.setBackground(new java.awt.Color(0, 125, 102));
        jLabelNenhumaTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNenhumaTarefa.setForeground(new java.awt.Color(0, 153, 102));
        jLabelNenhumaTarefa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNenhumaTarefa.setText("Nenhuma tarefa por aqui :D");

        jLabelCliqueNoBotao.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCliqueNoBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCliqueNoBotao.setText("Clique no botão \"+\" para adicionar uma nova tarefa");

        javax.swing.GroupLayout jPanelListaVaziaLayout = new javax.swing.GroupLayout(jPanelListaVazia);
        jPanelListaVazia.setLayout(jPanelListaVaziaLayout);
        jPanelListaVaziaLayout.setHorizontalGroup(
            jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaVaziaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCliqueNoBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNenhumaTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTarefaSelecionadaIconFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelListaVaziaLayout.setVerticalGroup(
            jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaVaziaLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabelTarefaSelecionadaIconFundo)
                .addGap(18, 18, 18)
                .addComponent(jLabelNenhumaTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCliqueNoBotao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JPanelFundoGeral.setBackground(new java.awt.Color(204, 204, 204));

        jPanelTopo.setBackground(new java.awt.Color(0, 153, 102));

        jLabelDeadLineApp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelDeadLineApp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDeadLineApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tick/tick (3).png"))); // NOI18N
        jLabelDeadLineApp.setText(" DeadLine App");

        jLabelAnote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAnote.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAnote.setText("Anote tudo, não esqueça de nada");

        javax.swing.GroupLayout jPanelTopoLayout = new javax.swing.GroupLayout(jPanelTopo);
        jPanelTopo.setLayout(jPanelTopoLayout);
        jPanelTopoLayout.setHorizontalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDeadLineApp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopoLayout.createSequentialGroup()
                        .addComponent(jLabelAnote, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGap(14, 14, 14))
        );
        jPanelTopoLayout.setVerticalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelDeadLineApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAnote)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanelFundoProjeto.setBackground(java.awt.Color.white);
        jPanelFundoProjeto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelProjetos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelProjetos.setForeground(new java.awt.Color(0, 153, 102));
        jLabelProjetos.setText("Projetos");

        jLabelProjetosAddIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProjetosAddIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add/add (5).png"))); // NOI18N
        jLabelProjetosAddIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProjetosAddIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelFundoProjetoLayout = new javax.swing.GroupLayout(jPanelFundoProjeto);
        jPanelFundoProjeto.setLayout(jPanelFundoProjetoLayout);
        jPanelFundoProjetoLayout.setHorizontalGroup(
            jPanelFundoProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjetos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabelProjetosAddIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelFundoProjetoLayout.setVerticalGroup(
            jPanelFundoProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundoProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFundoProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jLabelProjetosAddIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelFundoTarefa.setBackground(java.awt.Color.white);
        jPanelFundoTarefa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTarefas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTarefas.setForeground(new java.awt.Color(0, 153, 102));
        jLabelTarefas.setText("Tarefas");

        jLabelTarefasAddIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTarefasAddIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add/add (5).png"))); // NOI18N
        jLabelTarefasAddIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTarefasAddIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelFundoTarefaLayout = new javax.swing.GroupLayout(jPanelFundoTarefa);
        jPanelFundoTarefa.setLayout(jPanelFundoTarefaLayout);
        jPanelFundoTarefaLayout.setHorizontalGroup(
            jPanelFundoTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTarefasAddIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelFundoTarefaLayout.setVerticalGroup(
            jPanelFundoTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundoTarefaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFundoTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTarefasAddIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelFundoListaItem.setBackground(java.awt.Color.white);
        jPanelFundoListaItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jListProjetos.setBackground(java.awt.Color.white);
        jListProjetos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jListProjetos.setForeground(new java.awt.Color(51, 51, 51));
        jListProjetos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProjetos.setFixedCellHeight(40);
        jListProjetos.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jScrollPaneProjetos.setViewportView(jListProjetos);

        javax.swing.GroupLayout jPanelFundoListaItemLayout = new javax.swing.GroupLayout(jPanelFundoListaItem);
        jPanelFundoListaItem.setLayout(jPanelFundoListaItemLayout);
        jPanelFundoListaItemLayout.setHorizontalGroup(
            jPanelFundoListaItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoListaItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFundoListaItemLayout.setVerticalGroup(
            jPanelFundoListaItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoListaItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProjetos)
                .addContainerGap())
        );

        jPanelFundoTarefaSelecionada.setBackground(java.awt.Color.white);
        jPanelFundoTarefaSelecionada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableListaTarefas.setBackground(java.awt.Color.white);
        jTableListaTarefas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableListaTarefas.setForeground(new java.awt.Color(0, 153, 102));
        jTableListaTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaTarefas.setGridColor(new java.awt.Color(0, 153, 102));
        jTableListaTarefas.setRowHeight(50);
        jTableListaTarefas.setRowMargin(1);
        jTableListaTarefas.setRowSelectionAllowed(false);
        jTableListaTarefas.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTableListaTarefas.setShowHorizontalLines(true);
        jScrollPaneTarefas.setViewportView(jTableListaTarefas);

        javax.swing.GroupLayout jPanelFundoTarefaSelecionadaLayout = new javax.swing.GroupLayout(jPanelFundoTarefaSelecionada);
        jPanelFundoTarefaSelecionada.setLayout(jPanelFundoTarefaSelecionadaLayout);
        jPanelFundoTarefaSelecionadaLayout.setHorizontalGroup(
            jPanelFundoTarefaSelecionadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoTarefaSelecionadaLayout.createSequentialGroup()
                .addComponent(jScrollPaneTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFundoTarefaSelecionadaLayout.setVerticalGroup(
            jPanelFundoTarefaSelecionadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoTarefaSelecionadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPanelFundoGeralLayout = new javax.swing.GroupLayout(JPanelFundoGeral);
        JPanelFundoGeral.setLayout(JPanelFundoGeralLayout);
        JPanelFundoGeralLayout.setHorizontalGroup(
            JPanelFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFundoGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFundoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFundoListaItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelFundoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFundoTarefaSelecionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanelTopo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPanelFundoGeralLayout.setVerticalGroup(
            JPanelFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFundoGeralLayout.createSequentialGroup()
                .addComponent(jPanelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFundoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFundoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFundoListaItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFundoTarefaSelecionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelFundoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelFundoGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelProjetosAddIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjetosAddIconMouseClicked
        
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);
    }//GEN-LAST:event_jLabelProjetosAddIconMouseClicked

    private void jLabelTarefasAddIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTarefasAddIconMouseClicked
        
        TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
        //taskDialogScreen.setProject(null);
        taskDialogScreen.setVisible(true);
        
    }//GEN-LAST:event_jLabelTarefasAddIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelFundoGeral;
    private javax.swing.JLabel jLabelAnote;
    private javax.swing.JLabel jLabelCliqueNoBotao;
    private javax.swing.JLabel jLabelDeadLineApp;
    private javax.swing.JLabel jLabelNenhumaTarefa;
    private javax.swing.JLabel jLabelProjetos;
    private javax.swing.JLabel jLabelProjetosAddIcon;
    private javax.swing.JLabel jLabelTarefaSelecionadaIconFundo;
    private javax.swing.JLabel jLabelTarefas;
    private javax.swing.JLabel jLabelTarefasAddIcon;
    private javax.swing.JList<String> jListProjetos;
    private javax.swing.JPanel jPanelFundoListaItem;
    private javax.swing.JPanel jPanelFundoProjeto;
    private javax.swing.JPanel jPanelFundoTarefa;
    private javax.swing.JPanel jPanelFundoTarefaSelecionada;
    private javax.swing.JPanel jPanelListaVazia;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JScrollPane jScrollPaneProjetos;
    private javax.swing.JScrollPane jScrollPaneTarefas;
    private javax.swing.JTable jTableListaTarefas;
    // End of variables declaration//GEN-END:variables

    public void decorateTableTask() {
        jTableListaTarefas.getTableHeader().setFont(new Font("SEGOE UI", Font.BOLD, 14));
        jTableListaTarefas.getTableHeader().setBackground(new Color(0,153,102));
        jTableListaTarefas.getTableHeader().setForeground(new Color(255,255,255));
        jTableListaTarefas.setAutoCreateRowSorter(true);        
    }
    
    public void initDataController() {
        projectController = new ProjectController();
        taskController = new TaskController();
    }
    
    public void initComponentsModel() {
        projectModel = new DefaultListModel<Project>();
        loadProjects();
    }
    
    public void loadProjects() {
        List<Project> projects = projectController.getAll();
        
        //Limpa a estrutura que guarda os projetos
        projectModel.clear();
        
        for (int i = 0; i < projects.size() -1; i++) {
            Project project = projects.get(i);
            projectModel.addElement(project);
        }
        
        jListProjetos.setModel(projectModel);
    }
    
}
