/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author Avell
 */
public class ProjectDialogScreen extends javax.swing.JDialog {

    /**
     * Creates new form ProjectDialogScreen
     */
    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanelFundoGeral = new javax.swing.JPanel();
        jPanelTopo = new javax.swing.JPanel();
        jLabelProjeto = new javax.swing.JLabel();
        jLabelIconeProjeto = new javax.swing.JLabel();
        jPanelFundoCampos = new javax.swing.JPanel();
        jLabelNomeProjeto = new javax.swing.JLabel();
        jTextFieldNomeProjeto = new javax.swing.JTextField();
        jLabelDescricaoProjeto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricaoProjeto = new javax.swing.JTextArea();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 102));
        setResizable(false);

        jPanelFundoGeral.setBackground(new java.awt.Color(204, 204, 204));

        jPanelTopo.setBackground(new java.awt.Color(0, 153, 102));

        jLabelProjeto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelProjeto.setForeground(java.awt.Color.white);
        jLabelProjeto.setText("   Projeto");

        jLabelIconeProjeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconeProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check/check (5).png"))); // NOI18N

        javax.swing.GroupLayout jPanelTopoLayout = new javax.swing.GroupLayout(jPanelTopo);
        jPanelTopo.setLayout(jPanelTopoLayout);
        jPanelTopoLayout.setHorizontalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelIconeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanelTopoLayout.setVerticalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIconeProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabelProjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelFundoCampos.setBackground(java.awt.Color.white);

        jLabelNomeProjeto.setBackground(java.awt.Color.white);
        jLabelNomeProjeto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNomeProjeto.setForeground(new java.awt.Color(0, 153, 102));
        jLabelNomeProjeto.setText("Nome");

        jTextFieldNomeProjeto.setBackground(java.awt.Color.white);
        jTextFieldNomeProjeto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldNomeProjeto.setForeground(new java.awt.Color(0, 0, 0));

        jLabelDescricaoProjeto.setBackground(java.awt.Color.white);
        jLabelDescricaoProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescricaoProjeto.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescricaoProjeto.setText("Descrição");

        jTextAreaDescricaoProjeto.setBackground(java.awt.Color.white);
        jTextAreaDescricaoProjeto.setColumns(20);
        jTextAreaDescricaoProjeto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextAreaDescricaoProjeto.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaDescricaoProjeto.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricaoProjeto);

        javax.swing.GroupLayout jPanelFundoCamposLayout = new javax.swing.GroupLayout(jPanelFundoCampos);
        jPanelFundoCampos.setLayout(jPanelFundoCamposLayout);
        jPanelFundoCamposLayout.setHorizontalGroup(
            jPanelFundoCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundoCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFundoCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(jLabelNomeProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomeProjeto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescricaoProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelFundoCamposLayout.setVerticalGroup(
            jPanelFundoCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescricaoProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelFundoGeralLayout = new javax.swing.GroupLayout(jPanelFundoGeral);
        jPanelFundoGeral.setLayout(jPanelFundoGeralLayout);
        jPanelFundoGeralLayout.setHorizontalGroup(
            jPanelFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFundoCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanelTopo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanelFundoGeralLayout.setVerticalGroup(
            jPanelFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoGeralLayout.createSequentialGroup()
                .addComponent(jPanelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFundoCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundoGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDescricaoProjeto;
    private javax.swing.JLabel jLabelIconeProjeto;
    private javax.swing.JLabel jLabelNomeProjeto;
    private javax.swing.JLabel jLabelProjeto;
    private javax.swing.JPanel jPanelFundoCampos;
    private javax.swing.JPanel jPanelFundoGeral;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricaoProjeto;
    private javax.swing.JTextField jTextFieldNomeProjeto;
    // End of variables declaration//GEN-END:variables
}
