/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;

/**
 *
 * @author Avell
 */
public class TaskDialogScreen extends javax.swing.JDialog {

    /**
     * Creates new form ProjectDialogScreen
     */
    //Controlador para ser utilizado na tela inteira
    TaskController controller;
    //Criado para conseguir atribuir a chave estrangeira, ou seja, o projeto é o dono da tarefa
    //Cria o set no final
    Project project;

    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        //Cria o objeto de controlador no construtor
        controller = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanelFundoGeral = new javax.swing.JPanel();
        jPanelTopo = new javax.swing.JPanel();
        jLabelTarefa = new javax.swing.JLabel();
        jLabelIconSaveTarefa = new javax.swing.JLabel();
        jPanelFundoCampos = new javax.swing.JPanel();
        jLabelNomeTarefa = new javax.swing.JLabel();
        jTextFieldNomeTarefa = new javax.swing.JTextField();
        jLabelDescricaoTarefa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricaoTarefa = new javax.swing.JTextArea();
        jLabelPrazoTarefa = new javax.swing.JLabel();
        jLabelNotasTarefa = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNotasTarefa = new javax.swing.JTextArea();
        jFormattedTextFieldPrazoTarefa = new javax.swing.JFormattedTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 102));
        setResizable(false);

        jPanelFundoGeral.setBackground(new java.awt.Color(204, 204, 204));

        jPanelTopo.setBackground(new java.awt.Color(0, 153, 102));

        jLabelTarefa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTarefa.setForeground(java.awt.Color.white);
        jLabelTarefa.setText("   Tarefa");

        jLabelIconSaveTarefa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconSaveTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check/check (5).png"))); // NOI18N
        jLabelIconSaveTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconSaveTarefaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopoLayout = new javax.swing.GroupLayout(jPanelTopo);
        jPanelTopo.setLayout(jPanelTopoLayout);
        jPanelTopoLayout.setHorizontalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabelIconSaveTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanelTopoLayout.setVerticalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopoLayout.createSequentialGroup()
                .addComponent(jLabelIconSaveTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelFundoCampos.setBackground(java.awt.Color.white);

        jLabelNomeTarefa.setBackground(java.awt.Color.white);
        jLabelNomeTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNomeTarefa.setForeground(new java.awt.Color(0, 153, 102));
        jLabelNomeTarefa.setText("Nome");

        jTextFieldNomeTarefa.setBackground(java.awt.Color.white);
        jTextFieldNomeTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldNomeTarefa.setForeground(new java.awt.Color(0, 0, 0));

        jLabelDescricaoTarefa.setBackground(java.awt.Color.white);
        jLabelDescricaoTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescricaoTarefa.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDescricaoTarefa.setText("Descrição");

        jTextAreaDescricaoTarefa.setBackground(java.awt.Color.white);
        jTextAreaDescricaoTarefa.setColumns(20);
        jTextAreaDescricaoTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextAreaDescricaoTarefa.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaDescricaoTarefa.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricaoTarefa);

        jLabelPrazoTarefa.setBackground(java.awt.Color.white);
        jLabelPrazoTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrazoTarefa.setForeground(new java.awt.Color(0, 153, 102));
        jLabelPrazoTarefa.setText("Prazo");

        jLabelNotasTarefa.setBackground(java.awt.Color.white);
        jLabelNotasTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNotasTarefa.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNotasTarefa.setText("Notas");

        jTextAreaNotasTarefa.setBackground(java.awt.Color.white);
        jTextAreaNotasTarefa.setColumns(20);
        jTextAreaNotasTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextAreaNotasTarefa.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaNotasTarefa.setRows(5);
        jScrollPane2.setViewportView(jTextAreaNotasTarefa);

        jFormattedTextFieldPrazoTarefa.setBackground(java.awt.Color.white);
        jFormattedTextFieldPrazoTarefa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        javax.swing.GroupLayout jPanelFundoCamposLayout = new javax.swing.GroupLayout(jPanelFundoCampos);
        jPanelFundoCampos.setLayout(jPanelFundoCamposLayout);
        jPanelFundoCamposLayout.setHorizontalGroup(
            jPanelFundoCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFundoCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(jLabelNomeTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomeTarefa)
                    .addComponent(jLabelDescricaoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(jLabelPrazoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNotasTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldPrazoTarefa))
                .addContainerGap())
        );
        jPanelFundoCamposLayout.setVerticalGroup(
            jPanelFundoCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescricaoTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPrazoTarefa)
                .addGap(10, 10, 10)
                .addComponent(jFormattedTextFieldPrazoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNotasTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelFundoGeralLayout = new javax.swing.GroupLayout(jPanelFundoGeral);
        jPanelFundoGeral.setLayout(jPanelFundoGeralLayout);
        jPanelFundoGeralLayout.setHorizontalGroup(
            jPanelFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFundoCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanelTopo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, Short.MAX_VALUE)
        );
        jPanelFundoGeralLayout.setVerticalGroup(
            jPanelFundoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoGeralLayout.createSequentialGroup()
                .addComponent(jPanelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFundoCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundoGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelIconSaveTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconSaveTarefaMouseClicked

        try {
            Task task = new Task();
            task.setIdProject(18);
            
            //Cria a formatação para converter String em data
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            //Cria um objeto do tipo Date para receber essa String formatada
            Date deadline = null;
            //Atribui ao objeto do tipo Date a string formatada
            deadline = sdf.parse(jFormattedTextFieldPrazoTarefa.getText());
            //Seta essa data no Deadline(prazo) do projeot
            task.setDeadLine(deadline);

            task.setName(jTextFieldNomeTarefa.getText());
            task.setDescription(jTextAreaDescricaoTarefa.getText());

            task.setNotes(jTextAreaNotasTarefa.getText());
            task.setIsComplete(false);

            controller.save(task);
            JOptionPane.showMessageDialog(rootPane, "Tarefa salva com sucesso");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }

        this.dispose();

    }//GEN-LAST:event_jLabelIconSaveTarefaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldPrazoTarefa;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDescricaoTarefa;
    private javax.swing.JLabel jLabelIconSaveTarefa;
    private javax.swing.JLabel jLabelNomeTarefa;
    private javax.swing.JLabel jLabelNotasTarefa;
    private javax.swing.JLabel jLabelPrazoTarefa;
    private javax.swing.JLabel jLabelTarefa;
    private javax.swing.JPanel jPanelFundoCampos;
    private javax.swing.JPanel jPanelFundoGeral;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDescricaoTarefa;
    private javax.swing.JTextArea jTextAreaNotasTarefa;
    private javax.swing.JTextField jTextFieldNomeTarefa;
    // End of variables declaration//GEN-END:variables

    //Para referenciar ao projeto
    public void setProject(Project project) {
        this.project = project;
    }

    
    
}
